CREATE TABLE collection_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_id BIGINT NOT NULL,
    pokemon_id BIGINT NOT NULL,
    pokemon_name VARCHAR(255) NOT NULL,
    added_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_collection_entry_trainer
        FOREIGN KEY (trainer_id) REFERENCES trainer (id),
    CONSTRAINT uk_collection_entry_trainer_pokemon
        UNIQUE (trainer_id, pokemon_id)
);
